project:
  type: website
  output-dir: docs

website:
  title: "Jack Keller"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      
page-footer:
    left: |
      &copy; Jack Keller, 2023<br>
      All content licensed under <i class='bi-badge-cc'></i>
      [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Site built with <a href='https://quarto.org/'>Quarto</a>


format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

editor: visual

